$('body').append(''
    + '<div class="drawbox">'
    + '<label class="non-interactive">Geometry type &nbsp;</label>'
    + '<div>'
    + '  <select id="type">'
    + '    <option value="LineString">Line</option>'
    + '    <option value="Polygon">Marker Område</option>'
    + '    <option value="Circle">Sirkel</option>'
    + '  </select>'
    + '  <select id="color">'
    + '    <option value="Red">Red</option>'
    + '    <option value="Blue">Blue</option>'
    + '    <option value="Yellow">Yellow</option>'
    + '    <option value="Purple">Purple</option>'
    + '    <option value="Green">'
    + '  </select>'
    + '</div>'
    + '<div>'
    + '  <img src="images/draw_off.png" id="draw"/>'
    + '  <button id="addLayer">New Area</button>'
    + '  <button id="modifyLayer">Modify Area</button>'
    + '  <button id="snapToggle">Disable Snap</button>'
    + '</div'
    + '</div>'
)