$('body').append(''
    + '<div class="drawbox">'
    + '<label class="non-interactive">Geometry type &nbsp;</label>'
    + '<div>'
    + '  <select id="type">'
    + '    <option value="LineString">LineString</option>'
    + '    <option value="Polygon">Polygon</option>'
    + '    <option value="Circle">Circle</option>'
    + '  </select>'
    + '  <select id="color">'
    + '    <option value="Red">Red</option>'
    + '    <option value="Blue">Blue</option>'
    + '    <option value="Yellow">Yellow</option>'
    + '    <option value="Purple">Purple</option>'
    + '  </select>'
    + '</div>'
    + ''
    + '<button id="draw">Draw</button>'
    + '<button id ="addLayer">New Layer</button>'
    + '<button id ="resetlayer">Reset Layer</button>'
    + '</div>'
)